title: Gil Kim
description: Blog
author: Gil Kim
github: https://github.com/boogil
about: Android developer
disqus_shortname: boogil-github-io
# google_analytics: UA-72862926-1

collections:
  project:
    output: true
    permalink: /project/:path/

urls:
    - text: About Me
      url: /about/
    # - text: Projects
    #   url: /projects/
    - text: Resume
      url: https://drive.google.com/file/d/1uDYyrD0FSq_6SQaXkuvq0GqAkAN89Pmj/view
    - text: Github
      url: https://github.com/boogil
    - text: XML Feed
      url: /feed.xml

# social:
#     - icon: fa-facebook
#       link: http://facebook.com/ashutosh2k12
#     - icon: fa-skype
#       link: skype:ashu2k111
#     - icon: fa-twitter
#       link: http://twitter.com/216ashutosh
#     - icon: fa-linkedin
#       link: https://in.linkedin.com/in/codeasashu
#     - icon: fa-stack-exchange
#       link: http://stackexchange.com/users/1155850/ashutosh

share:
  twitter_username: 216ashutosh
  fb_appid: 1159707894060864


enableTags: true
tagarray: []

# url: "http://aboutashu.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
